### ISSUE TITLE
link from code page to github seems not to be working

### ISSUE THREAD

**Issue by andysouth** [afrimapr/afrimapr.website#3]
Although the link is written correctly in code.md (https://github.com/afrimapr).

When I click on it from the website it remains on afrimapr.org

I wonder if this could be due to the domain specification, i.e. that it is hiding the true URL.

**Comment by andysouth** [comment]
@anelda 

Does adding this after the link work ? {:target="_blank"}

Or you may need to do <a href="http://example.com/" target="_blank">Hello, world!</a>
see

**Comment by anelda** [comment]
I tried it, but I think there's something wrong with the way the custom domain is resolving links. When I click for example on the team page, it still only shows afrimapr.org in the address bar. What it should do is show afrimapr.org/team. The urls work correctly in afrimapr.github.io/afrimapr.website. Still looking around for tips. Let me know if you find something

**Comment by anelda** [comment]
Seems to be resolving on Chrome but not Firefox for me. I get 

> Blocked by Content Security Policy

An error occurred during a connection to github.com.

Firefox prevented this page from loading in this way because the page has a content security policy that disallows it.

**Comment by andysouth** [comment]
I changed the domain to point to https://afrimapr.github.io/afrimapr.website/  (the support person explicitly told me to use http).
It seems to work fine for me now, i.e. the link to github works.
I also tried turning off domain hiding and that seemed to work OK too but seems like may not be necessary.
@anelda Can you try out how it works for you now ?

**Comment by anelda** [comment]
Thanks Andy! works like a charm for me. We can close this I think.
